---

plugins: [flowtype]

env:
  jest: true
  browser: true
  node: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:flowtype/recommended
